# conda env create --file environment.yml
name: 'py'
channels:
  - conda-forge
dependencies:
  - python = 3.12
  - pip
  
  # Conda packages
  - ipykernel # for use with Jupyter
  - pandas=1.26.4
  - numpy=2.2.2

  
  ## PyPI packages
  - pip: 
    - plotly=5.22.0
    - ipywidgets>=7.6
    - python-dotenv==1.0.1
    - scipy==1.12
    - nbformat==5.10.4
    - matplotlib==3.9.0
    - kaleido==0.2.1
    
